DROP TABLE IF EXISTS owners;
DROP TABLE IF EXISTS pets;

CREATE TABLE owners(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  age INTEGER
);

CREATE TABLE pets(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  animal_type TEXT,
  owner_id INTEGER REFERENCES owners ON
DELETE CASCADE
);